In [0]:
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
import numpy as np

In [6]:
#fibonacci-series 
a = tf.Variable(1,tf.int32)
b = tf.Variable(1,tf.int32)
temp = tf.Variable(1,tf.int32)

assign1 = tf.assign(temp,a)
assign2 = tf.assign(a,b)
assign3 = tf.assign(b,temp+b)

with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    print(a.eval())
    print(b.eval())
    for i in range(0,10):
        print(sess.run(assign1))
        print(sess.run(assign2))
        print(sess.run(assign3))

1
1
1
1
2
1
2
3
2
3
5
3
5
8
5
8
13
8
13
21
13
21
34
21
34
55
34
55
89
55
89
144


In [7]:
#optimizer use
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np
n_samples=1000
n_dims=10
X_data=np.random.rand(n_samples,n_dims)
Tw=np.random.rand(n_dims,1)
Y_data=np.matmul(X_data,Tw)+np.random.rand(n_samples,1) #adding bias to each row of dataset
print(Y_data[:2])
print(Tw)
batch_size=100
X=tf.placeholder(tf.float32,shape=(batch_size,n_dims))
Y=tf.placeholder(tf.float32,shape=(batch_size,1))
W=tf.Variable(np.random.rand(n_dims,1),dtype=tf.float32)
Y_hat=tf.matmul(X,W)
loss=tf.reduce_mean((Y-Y_hat)**2/n_samples) #single scalar loss value
optimizer=tf.train.AdamOptimizer().minimize(loss)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(10000):
        indices=np.random.choice(n_samples,batch_size)
        X_batch=X_data[indices] #subsetting
        Y_batch=Y_data[indices]
        e,error,weight=sess.run([optimizer,loss,W],feed_dict={X:X_batch,Y:Y_batch})
        if i%5000==0:
            print(error)
            print(weight)

Instructions for updating:
non-resource variables are not supported in the long term
[[3.53876152]
 [3.33963414]]
[[0.97789851]
 [0.95276515]
 [0.16399433]
 [0.45261245]
 [0.60351509]
 [0.01478087]
 [0.24310971]
 [0.70918211]
 [0.60425362]
 [0.73225885]]
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
0.00027839822
[[0.22255766]
 [0.8999582 ]
 [0.7409876 ]
 [0.96946627]
 [0.24587756]
 [0.70865583]
 [0.9869483 ]
 [0.6801644 ]
 [0.31898198]
 [0.5063618 ]]
0.0001169526
[[1.1003811 ]
 [0.9941399 ]
 [0.27978998]
 [0.59001505]
 [0.7006757 ]
 [0.12001094]
 [0.31085   ]
 [0.7911778 ]
 [0.7142562 ]
 [0.8089591 ]]
